[theme]

# Primary accent for interactive elements
primaryColor = '#289471'

# Background color for the main content area
backgroundColor = '#242254'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#008600'

# Color used for almost all text
textColor = '#FFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false